services:
  - type: web
    name: voting-app
    runtime: docker
    region: singapore
    plan: free
    branch: master
    repo: https://github.com/sohel87399/terraform_k8s_deployment # Update this if your repo URL is different
    envVars:
      - key: PORT
        value: 80
